version: 2.1

orbs:
  vault: jeffwecan/vault-auth-circleci@dev:alpha

references:
  urls:
    vault: &VAULT_ADDR https://lately-up-jaguar.waypoint.run

jobs:
  lookup-token:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: vault token lookup -address='https://lately-up-jaguar.waypoint.run'
      - run: vault token lookup -address='*VAULT_ADDR'
workflows:
  main:
    jobs:
      - vault/login:
          vault-addr: *VAULT_ADDR
      - lookup-token:
          requires:
            - vault/login
