version: 2.1
orbs:
  vault: jeffwecan/vault-auth-circleci@dev:2df4433
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - vault/install
      - vault/login:
          vault-addr: "https://strongly-aware-elf.waypoint.run"
      - run: vault token lookup -address="https://strongly-aware-elf.waypoint.run"
workflows:
  main:
    jobs:
      - build
