version: 2.0
jobs:
  build:
    working_directory: ~/vault-circleci-auth-plugin
    docker:
      - image: hashicorp/vault
    steps:
      - checkout
      - run:
          name: Attempt to authenticate
          command: |
            set -e

            export VAULT_ADDR='https://strongly-aware-elf.waypoint.run'
            vault write auth/circleci/login \
                project="$CIRCLE_PROJECT_REPONAME" \
                build_num="$CIRCLE_BUILD_NUM" \
                vcs_revision="$CIRCLE_SHA1"
