version: 2.1

orbs:
  vault: jeffwecan/vault-auth-circleci@dev:5f4fa63


references:
  urls:
    vault: &VAULT_ADDR https://lately-up-jaguar.waypoint.run

jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - vault/install
      - run: sleep 600
      - vault/login:
          vault-addr: *VAULT_ADDR
      - run: vault token lookup -address='https://lately-up-jaguar.waypoint.run'
      - run: vault token lookup -address='*VAULT_ADDR'
workflows:
  main:
    jobs:
      - build
